### ISSUE TITLE
error after npm test

### ISSUE THREAD

**Issue by moneymour** [gothinkster/gcp-datastore-cloud-functions-realworld-example-app#12]
Hello,

 i have this error when try to run npm test

npm ERR! Failed at the @ test:unit script 'DATASTORE_NAMESPACE=test-unit-`date +%s` nyc mocha --opts .mochaopts ./src/*.test.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     DATASTORE_NAMESPACE=test-unit-`date +%s` nyc mocha --opts .mochaopts ./src/*.test.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

my node version is v6.11.5

we can help me to resolve ?

thanks

**Comment by anishkny** [comment]
Hi @moneymour 

This repo needs Node.js version 8 or greater.

Did you follow the steps listed in [Getting Started](https://github.com/gothinkster/gcp-datastore-cloud-functions-realworld-example-app#getting-started)?

Are you on Windows? Currently only Linux/Mac are supported.

**Comment by moneymour** [comment]
Hi @anishkny  thanks for the support.

i use Node.js v6.11.5 because Google functions don't support other versions.

Yes i follow the steps in "Getting Started". 

i'm Mac user

**Comment by anishkny** [comment]
Since this repo uses features like `async/await`, Node.js 8.0 or greater is required. Before deploying to Cloud Functions it uses `babel` to transpile down to Node 6.0. See [doc](https://github.com/gothinkster/gcp-datastore-cloud-functions-realworld-example-app#deploy-to-cloud-functions).

Please consider upgrading to Node.js 8 or [creationix/nvm](https://github.com/creationix/nvm) to manage multiple Node.js versions on the same machine.

Added to doc: https://github.com/gothinkster/gcp-datastore-cloud-functions-realworld-example-app/commit/0f34161d20629a1eb314ed2a5d7a9060619b5d88
